# OLS Regression

In [1]:
import pandas as pd
import seaborn as sns
import numpy as np
import matplotlib.pyplot as plt
import statsmodels.api as sm
from sklearn.model_selection import train_test_split 

In [2]:
#read csv -  
OLS_two = pd.read_csv('two_thousand.csv') 
OLS_two

artist_names  danceability  energy  valence    tempo  \
0          "Fat Freddy's Drop"         0.600   0.365    0.131  130.046   
1          "Fat Freddy's Drop"         0.670   0.531    0.336  139.385   
2      "Colby O'Donis", 'Akon'         0.775   0.641    0.305  119.974   
3      "Colby O'Donis", 'Akon'         0.775   0.641    0.305  119.974   
4              "Colby O'Donis"         0.773   0.639    0.310  119.970   
...                        ...           ...     ...      ...      ...   
20351          'Zion & Lennox'         0.686   0.877    0.877  192.008   
20352          'Zion & Lennox'         0.807   0.781    0.536   95.009   
20353                 'ZZ Top'         0.469   0.532    0.520  160.914   
20354                 'ZZ Top'         0.552   0.651    0.533  161.548   
20355                 'ZZ Top'         0.546   0.864    0.863  145.652   

       loudness  mode  key  acousticness  instrumentalness  liveness  \
0       -13.083     0    9       0.06720           0.58500    0.0921   
1        -8.267     0    9       0.01560           0.34500    0.3060   
2        -6.718     1    1       0.03270           0.00000    0.1800   
3        -6.718     1    1       0.03270           0.00000    0.1800   
4        -6.738     1    1       0.03330           0.00000    0.1660   
...         ...   ...  ...           ...               ...       ...   
20351    -5.848     1    8       0.00221           0.24300    0.1080   
20352    -6.028     1    1       0.07840           0.00000    0.1050   
20353   -15.666     0    9       0.01280           0.12500    0.1180   
20354   -10.624     0    4       0.00494           0.03490    0.1320   
20355    -7.632     1    7       0.09080           0.00814    0.2770   

       speechiness  explicit  duration_ms  popularity  year  \
0           0.0498         0       437200          54  2005   
1           0.0377         0       431293          55  2009   
2           0.0380         0       243013          57  2008   
3           0.0380         0       243013          57  2008   
4           0.0380         0       243240          44  2008   
...            ...       ...          ...         ...   ...   
20351       0.1310         0       210024          54  2004   
20352       0.1580         0       192000          56  2004   
20353       0.0609         0       234107          37  2005   
20354       0.2290         0       232533          56  2004   
20355       0.0393         0       137240          43  2005   

                      song_title       Genre  decade  is_popular  
0                          Ernie  Electronic    2000           1  
1                       The Raft  Electronic    2000           1  
2            What You Got - Main        R&B;    2000           1  
3            What You Got - Main        R&B;    2000           1  
4      What You Got (feat. Akon)        R&B;    2000           0  
...                          ...         ...     ...         ...  
20351                   Doncella       Latin    2000           1  
20352                    Bandida       Latin    2000           1  
20353                  La Grange    Pop/Rock    2000           0  
20354  La Grange - **** Remaster    Pop/Rock    2000           1  
20355                       ****    Pop/Rock    2000           0  

[20356 rows x 20 columns]

In [3]:
OLS_two = OLS_two.drop(['artist_names',"year","song_title","decade","Genre","is_popular"],axis = 1)

In [4]:
df = OLS_two.copy()
X = df.drop(columns="popularity")
y = df['popularity']

In [5]:
X = sm.add_constant(X)

In [6]:
model = sm.OLS(y, X).fit()

In [7]:
predictions = model.predict(X) 
print_model = model.summary()
print(print_model)

                            OLS Regression Results                            
Dep. Variable:             popularity   R-squared:                       0.068
Model:                            OLS   Adj. R-squared:                  0.067
Method:                 Least Squares   F-statistic:                     114.0
Date:                Wed, 17 Mar 2021   Prob (F-statistic):          3.93e-298
Time:                        01:01:12   Log-Likelihood:                -76761.
No. Observations:               20356   AIC:                         1.535e+05
Df Residuals:                   20342   BIC:                         1.537e+05
Df Model:                          13                                         
Covariance Type:            nonrobust                                         
                       coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------------
const               64.2854      0.955  

# Logistic Regression

In [77]:
LR = pd.read_csv('two_thousand.csv')
LR.head()

artist_names  danceability  energy  valence    tempo  loudness  \
0      "Fat Freddy's Drop"         0.600   0.365    0.131  130.046   -13.083   
1      "Fat Freddy's Drop"         0.670   0.531    0.336  139.385    -8.267   
2  "Colby O'Donis", 'Akon'         0.775   0.641    0.305  119.974    -6.718   
3  "Colby O'Donis", 'Akon'         0.775   0.641    0.305  119.974    -6.718   
4          "Colby O'Donis"         0.773   0.639    0.310  119.970    -6.738   

   mode  key  acousticness  instrumentalness  liveness  speechiness  explicit  \
0     0    9        0.0672             0.585    0.0921       0.0498         0   
1     0    9        0.0156             0.345    0.3060       0.0377         0   
2     1    1        0.0327             0.000    0.1800       0.0380         0   
3     1    1        0.0327             0.000    0.1800       0.0380         0   
4     1    1        0.0333             0.000    0.1660       0.0380         0   

   duration_ms  popularity  year                 song_title       Genre  \
0       437200          54  2005                      Ernie  Electronic   
1       431293          55  2009                   The Raft  Electronic   
2       243013          57  2008        What You Got - Main        R&B;   
3       243013          57  2008        What You Got - Main        R&B;   
4       243240          44  2008  What You Got (feat. Akon)        R&B;   

   decade  is_popular  
0    2000           1  
1    2000           1  
2    2000           1  
3    2000           1  
4    2000           0

In [78]:
LR = LR.drop(['artist_names','key','mode','explicit','year','song_title','popularity','decade','Genre'],axis = 1)
LR['duration_ms'] = LR['duration_ms']/1000
LR.head()

danceability  energy  valence    tempo  loudness  acousticness  \
0         0.600   0.365    0.131  130.046   -13.083        0.0672   
1         0.670   0.531    0.336  139.385    -8.267        0.0156   
2         0.775   0.641    0.305  119.974    -6.718        0.0327   
3         0.775   0.641    0.305  119.974    -6.718        0.0327   
4         0.773   0.639    0.310  119.970    -6.738        0.0333   

   instrumentalness  liveness  speechiness  duration_ms  is_popular  
0             0.585    0.0921       0.0498      437.200           1  
1             0.345    0.3060       0.0377      431.293           1  
2             0.000    0.1800       0.0380      243.013           1  
3             0.000    0.1800       0.0380      243.013           1  
4             0.000    0.1660       0.0380      243.240           0

In [79]:
y = LR["is_popular"]
X = LR.drop(columns="is_popular")

In [80]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42, stratify=y)

In [81]:
from sklearn.linear_model import LogisticRegression
LR_classifier = LogisticRegression(solver='lbfgs',
   max_iter=100000,
   random_state=42)

In [82]:
LR_classifier.fit(X_train, y_train)

LogisticRegression(max_iter=100000, random_state=42)

In [83]:
y_pred = LR_classifier.predict(X_test)

In [84]:
from sklearn.metrics import accuracy_score
LR_accuracy=accuracy_score(y_test, y_pred)

In [85]:
print("Accuracy: " + str(LR_accuracy))

Accuracy: 0.640793869129495


In [86]:
from sklearn.metrics import confusion_matrix, classification_report
matrix = confusion_matrix(y_test, y_pred)
print(matrix)

[[ 112 1689]
 [ 139 3149]]


In [87]:
report = classification_report(y_test, y_pred)
print(report)

              precision    recall  f1-score   support

           0       0.45      0.06      0.11      1801
           1       0.65      0.96      0.78      3288

    accuracy                           0.64      5089
   macro avg       0.55      0.51      0.44      5089
weighted avg       0.58      0.64      0.54      5089



# SVM

In [88]:
svm = pd.read_csv('two_thousand.csv')

In [89]:
svm = svm.drop(['artist_names','key','mode','explicit','year','song_title','popularity','decade','Genre'],axis = 1)
svm['duration_ms'] = svm['duration_ms']/1000
svm.head()

danceability  energy  valence    tempo  loudness  acousticness  \
0         0.600   0.365    0.131  130.046   -13.083        0.0672   
1         0.670   0.531    0.336  139.385    -8.267        0.0156   
2         0.775   0.641    0.305  119.974    -6.718        0.0327   
3         0.775   0.641    0.305  119.974    -6.718        0.0327   
4         0.773   0.639    0.310  119.970    -6.738        0.0333   

   instrumentalness  liveness  speechiness  duration_ms  is_popular  
0             0.585    0.0921       0.0498      437.200           1  
1             0.345    0.3060       0.0377      431.293           1  
2             0.000    0.1800       0.0380      243.013           1  
3             0.000    0.1800       0.0380      243.013           1  
4             0.000    0.1660       0.0380      243.240           0

In [90]:
y = svm["is_popular"]
X = svm.drop(columns="is_popular")

In [91]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,
   y,  random_state=1, stratify=y)
X_train.shape

(15267, 10)

In [92]:
from sklearn.svm import SVC
svm_model = SVC(kernel='linear')

In [93]:
svm_model.fit(X_train, y_train)

SVC(kernel='linear')

In [94]:
y_pred = svm_model.predict(X_test)
results = pd.DataFrame({
   "Prediction": y_pred,
   "Actual": y_test
}).reset_index(drop=True)
results.head()

Prediction  Actual
0           1       0
1           1       1
2           1       1
3           1       1
4           1       1

In [95]:
svm_accuracy=accuracy_score(y_test, y_pred)

In [96]:
print("Accuracy: " + str(svm_accuracy))

Accuracy: 0.6457064256238947


In [97]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, y_pred)

from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.00      0.00      0.00      1801
           1       0.65      1.00      0.78      3288

    accuracy                           0.65      5089
   macro avg       0.32      0.50      0.39      5089
weighted avg       0.42      0.65      0.51      5089



# Encode/Scale and Normalize Data


In [98]:
genre = pd.read_csv('two_thousand.csv')
genre.head()

artist_names  danceability  energy  valence    tempo  loudness  \
0      "Fat Freddy's Drop"         0.600   0.365    0.131  130.046   -13.083   
1      "Fat Freddy's Drop"         0.670   0.531    0.336  139.385    -8.267   
2  "Colby O'Donis", 'Akon'         0.775   0.641    0.305  119.974    -6.718   
3  "Colby O'Donis", 'Akon'         0.775   0.641    0.305  119.974    -6.718   
4          "Colby O'Donis"         0.773   0.639    0.310  119.970    -6.738   

   mode  key  acousticness  instrumentalness  liveness  speechiness  explicit  \
0     0    9        0.0672             0.585    0.0921       0.0498         0   
1     0    9        0.0156             0.345    0.3060       0.0377         0   
2     1    1        0.0327             0.000    0.1800       0.0380         0   
3     1    1        0.0327             0.000    0.1800       0.0380         0   
4     1    1        0.0333             0.000    0.1660       0.0380         0   

   duration_ms  popularity  year                 song_title       Genre  \
0       437200          54  2005                      Ernie  Electronic   
1       431293          55  2009                   The Raft  Electronic   
2       243013          57  2008        What You Got - Main        R&B;   
3       243013          57  2008        What You Got - Main        R&B;   
4       243240          44  2008  What You Got (feat. Akon)        R&B;   

   decade  is_popular  
0    2000           1  
1    2000           1  
2    2000           1  
3    2000           1  
4    2000           0

In [99]:
genre = genre.drop(["artist_names",'explicit','key','mode','popularity','song_title','decade',"year"],axis = 1)
genre['duration_ms'] = genre['duration_ms']/1000
genre.head()

danceability  energy  valence    tempo  loudness  acousticness  \
0         0.600   0.365    0.131  130.046   -13.083        0.0672   
1         0.670   0.531    0.336  139.385    -8.267        0.0156   
2         0.775   0.641    0.305  119.974    -6.718        0.0327   
3         0.775   0.641    0.305  119.974    -6.718        0.0327   
4         0.773   0.639    0.310  119.970    -6.738        0.0333   

   instrumentalness  liveness  speechiness  duration_ms       Genre  \
0             0.585    0.0921       0.0498      437.200  Electronic   
1             0.345    0.3060       0.0377      431.293  Electronic   
2             0.000    0.1800       0.0380      243.013        R&B;   
3             0.000    0.1800       0.0380      243.013        R&B;   
4             0.000    0.1660       0.0380      243.240        R&B;   

   is_popular  
0           1  
1           1  
2           1  
3           1  
4           0

In [100]:
genre_binary_encoded = pd.get_dummies(genre, columns=["Genre"])
genre_binary_encoded.head()

danceability  energy  valence    tempo  loudness  acousticness  \
0         0.600   0.365    0.131  130.046   -13.083        0.0672   
1         0.670   0.531    0.336  139.385    -8.267        0.0156   
2         0.775   0.641    0.305  119.974    -6.718        0.0327   
3         0.775   0.641    0.305  119.974    -6.718        0.0327   
4         0.773   0.639    0.310  119.970    -6.738        0.0333   

   instrumentalness  liveness  speechiness  duration_ms  ...  \
0             0.585    0.0921       0.0498      437.200  ...   
1             0.345    0.3060       0.0377      431.293  ...   
2             0.000    0.1800       0.0380      243.013  ...   
3             0.000    0.1800       0.0380      243.013  ...   
4             0.000    0.1660       0.0380      243.240  ...   

   Genre_International  Genre_Jazz  Genre_Latin  Genre_New Age  \
0                    0           0            0              0   
1                    0           0            0              0   
2                    0           0            0              0   
3                    0           0            0              0   
4                    0           0            0              0   

   Genre_Pop/Rock  Genre_R&B;  Genre_Reggae  Genre_Religious  \
0               0           0             0                0   
1               0           0             0                0   
2               0           1             0                0   
3               0           1             0                0   
4               0           1             0                0   

   Genre_Stage & Screen  Genre_Vocal  
0                     0            0  
1                     0            0  
2                     0            0  
3                     0            0  
4                     0            0  

[5 rows x 30 columns]

In [101]:
from sklearn.preprocessing import StandardScaler
data_scaler = StandardScaler()

In [102]:
loans_data_scaled = data_scaler.fit_transform(genre_binary_encoded)

In [103]:
loans_data_scaled[:5]

array([[ 2.00419048e-01, -1.42942127e+00, -1.54560661e+00,
         2.71922546e-01, -1.93357598e+00, -5.63913390e-01,
         3.01615781e+00, -6.66435857e-01, -3.04906183e-01,
         3.36625312e+00,  7.40180439e-01, -2.52792495e-02,
        -4.43721930e-02, -2.42869204e-02, -4.15012793e-02,
        -2.62341618e-02, -3.43199583e-01, -2.97496685e-02,
         5.00306811e+00, -5.06070322e-02, -6.08115326e-02,
        -8.61599534e-02, -2.38088317e-01, -4.65425307e-02,
        -1.23310775e+00, -3.83335538e-01, -1.13523106e-01,
        -1.39761248e-01, -9.93604593e-02, -8.55793909e-02],
       [ 6.44128484e-01, -6.66843080e-01, -6.87623023e-01,
         5.88203570e-01, -4.64367506e-01, -7.50596801e-01,
         1.65305285e+00,  9.29712054e-01, -5.40962372e-01,
         3.26760799e+00,  7.40180439e-01, -2.52792495e-02,
        -4.43721930e-02, -2.42869204e-02, -4.15012793e-02,
        -2.62341618e-02, -3.43199583e-01, -2.97496685e-02,
         5.00306811e+00, -5.06070322e-02, -6.08115326e-

In [104]:
import numpy as np
print(np.mean(loans_data_scaled[:,0]))
print(np.std(loans_data_scaled[:,0]))

1.39623253244272e-17
0.9999999999999998


# DecisionTree

In [36]:
# Initial imports
import pandas as pd
from path import Path
from sklearn import tree
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

In [105]:
# Define the features set.
X = genre_binary_encoded.copy()
X = X.drop(["is_popular"], axis=1)
X.head()

danceability  energy  valence    tempo  loudness  acousticness  \
0         0.600   0.365    0.131  130.046   -13.083        0.0672   
1         0.670   0.531    0.336  139.385    -8.267        0.0156   
2         0.775   0.641    0.305  119.974    -6.718        0.0327   
3         0.775   0.641    0.305  119.974    -6.718        0.0327   
4         0.773   0.639    0.310  119.970    -6.738        0.0333   

   instrumentalness  liveness  speechiness  duration_ms  ...  \
0             0.585    0.0921       0.0498      437.200  ...   
1             0.345    0.3060       0.0377      431.293  ...   
2             0.000    0.1800       0.0380      243.013  ...   
3             0.000    0.1800       0.0380      243.013  ...   
4             0.000    0.1660       0.0380      243.240  ...   

   Genre_International  Genre_Jazz  Genre_Latin  Genre_New Age  \
0                    0           0            0              0   
1                    0           0            0              0   
2                    0           0            0              0   
3                    0           0            0              0   
4                    0           0            0              0   

   Genre_Pop/Rock  Genre_R&B;  Genre_Reggae  Genre_Religious  \
0               0           0             0                0   
1               0           0             0                0   
2               0           1             0                0   
3               0           1             0                0   
4               0           1             0                0   

   Genre_Stage & Screen  Genre_Vocal  
0                     0            0  
1                     0            0  
2                     0            0  
3                     0            0  
4                     0            0  

[5 rows x 29 columns]

In [106]:
# Define the target set.
y = genre_binary_encoded["is_popular"].values
y[:5]

array([1, 1, 1, 1, 0], dtype=int64)

In [107]:
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=78)

In [108]:
# Determine the shape of our training and testing sets.
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(15267, 29)
(5089, 29)
(15267,)
(5089,)


In [109]:
# Creating a StandardScaler instance.
scaler = StandardScaler()
# Fitting the Standard Scaler with the training data.
X_scaler = scaler.fit(X_train)

# Scaling the data.
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [110]:
# Creating the decision tree classifier instance.
dt_model = tree.DecisionTreeClassifier()
# Fitting the model.
dt_model = dt_model.fit(X_train_scaled, y_train)

In [111]:
# Making predictions using the testing data.
predictions = dt_model.predict(X_test_scaled)
predictions

array([1, 1, 1, ..., 1, 1, 0], dtype=int64)

In [112]:
# Calculating the confusion matrix
dt_cm = confusion_matrix(y_test, predictions)

# Create a DataFrame from the confusion matrix.
dt_cm_df = pd.DataFrame(
    dt_cm, index=["Actual 0", "Actual 1"], columns=["Predicted 0", "Predicted 1"])

dt_cm_df

Predicted 0  Predicted 1
Actual 0          785         1002
Actual 1         1041         2261

In [113]:
# Calculating the accuracy score.
dt_acc_score = accuracy_score(y_test, predictions)

In [114]:
# Displaying results
print("Confusion Matrix")
display(dt_cm_df)
print("Accuracy: " + str(dt_acc_score))
print("Classification Report")
print(classification_report(y_test, predictions))

Confusion Matrix


Predicted 0  Predicted 1
Actual 0          785         1002
Actual 1         1041         2261

Accuracy: 0.5985458832776577
Classification Report
              precision    recall  f1-score   support

           0       0.43      0.44      0.43      1787
           1       0.69      0.68      0.69      3302

    accuracy                           0.60      5089
   macro avg       0.56      0.56      0.56      5089
weighted avg       0.60      0.60      0.60      5089



# RandomForestClassifier

In [47]:
# Initial imports.
import pandas as pd
from path import Path
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

In [115]:
# Define the features set.
X = genre_binary_encoded.copy()
X = X.drop(["is_popular"], axis=1)
X.head()

danceability  energy  valence    tempo  loudness  acousticness  \
0         0.600   0.365    0.131  130.046   -13.083        0.0672   
1         0.670   0.531    0.336  139.385    -8.267        0.0156   
2         0.775   0.641    0.305  119.974    -6.718        0.0327   
3         0.775   0.641    0.305  119.974    -6.718        0.0327   
4         0.773   0.639    0.310  119.970    -6.738        0.0333   

   instrumentalness  liveness  speechiness  duration_ms  ...  \
0             0.585    0.0921       0.0498      437.200  ...   
1             0.345    0.3060       0.0377      431.293  ...   
2             0.000    0.1800       0.0380      243.013  ...   
3             0.000    0.1800       0.0380      243.013  ...   
4             0.000    0.1660       0.0380      243.240  ...   

   Genre_International  Genre_Jazz  Genre_Latin  Genre_New Age  \
0                    0           0            0              0   
1                    0           0            0              0   
2                    0           0            0              0   
3                    0           0            0              0   
4                    0           0            0              0   

   Genre_Pop/Rock  Genre_R&B;  Genre_Reggae  Genre_Religious  \
0               0           0             0                0   
1               0           0             0                0   
2               0           1             0                0   
3               0           1             0                0   
4               0           1             0                0   

   Genre_Stage & Screen  Genre_Vocal  
0                     0            0  
1                     0            0  
2                     0            0  
3                     0            0  
4                     0            0  

[5 rows x 29 columns]

In [116]:
# Define the target set.
y = genre_binary_encoded["is_popular"].ravel()
y[:5]

array([1, 1, 1, 1, 0], dtype=int64)

In [117]:
# Splitting into Train and Test sets.
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=78)

In [118]:
# Creating a StandardScaler instance.
scaler = StandardScaler()
# Fitting the Standard Scaler with the training data.
X_scaler = scaler.fit(X_train)

# Scaling the data.
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [119]:
# Create a random forest classifier.
rf_model = RandomForestClassifier(n_estimators=128, random_state=78) 

In [120]:
# Fitting the model
rf_model = rf_model.fit(X_train_scaled, y_train)

In [121]:
# Making predictions using the testing data.
rf_predictions = rf_model.predict(X_test_scaled)
rf_predictions

array([1, 1, 1, ..., 1, 1, 1], dtype=int64)

In [122]:
# Calculating the confusion matrix.
rf_cm = confusion_matrix(y_test, rf_predictions)

# Create a DataFrame from the confusion matrix.
rf_cm_df = pd.DataFrame(
    rf_cm, index=["Actual 0", "Actual 1"], columns=["Predicted 0", "Predicted 1"])

rf_cm_df

Predicted 0  Predicted 1
Actual 0          466         1321
Actual 1          408         2894

In [123]:
# Calculating the accuracy score.
rf_acc_score = accuracy_score(y_test, rf_predictions)

In [124]:
# Displaying results
print("Confusion Matrix")
display(rf_cm_df)
print("Accuracy: " + str(rf_acc_score))
print("Classification Report")
print(classification_report(y_test, rf_predictions))

Confusion Matrix


Predicted 0  Predicted 1
Actual 0          466         1321
Actual 1          408         2894

Accuracy: 0.6602475928473177
Classification Report
              precision    recall  f1-score   support

           0       0.53      0.26      0.35      1787
           1       0.69      0.88      0.77      3302

    accuracy                           0.66      5089
   macro avg       0.61      0.57      0.56      5089
weighted avg       0.63      0.66      0.62      5089



In [125]:
# Calculate feature importance in the Random Forest model.
importances = rf_model.feature_importances_
importances

array([0.09853396, 0.09830388, 0.09559728, 0.0933658 , 0.10381612,
       0.09700901, 0.0755325 , 0.09324263, 0.09548962, 0.10305542,
       0.00011265, 0.00072811, 0.00021811, 0.00030479, 0.0002187 ,
       0.00748564, 0.00022156, 0.00412685, 0.00070932, 0.00083491,
       0.00202685, 0.00555867, 0.00038523, 0.00927615, 0.00613441,
       0.00158511, 0.00364632, 0.00123416, 0.00124624])

In [126]:
# We can sort the features by their importance.
sorted(zip(rf_model.feature_importances_, X.columns), reverse=True)

[(0.10381611726127174, 'loudness'),
 (0.10305541539148473, 'duration_ms'),
 (0.09853395930427129, 'danceability'),
 (0.09830388125126656, 'energy'),
 (0.09700900755792458, 'acousticness'),
 (0.09559727788807874, 'valence'),
 (0.09548962152447758, 'speechiness'),
 (0.09336580177981106, 'tempo'),
 (0.09324263035029814, 'liveness'),
 (0.07553250471353647, 'instrumentalness'),
 (0.009276154967561331, 'Genre_Pop/Rock'),
 (0.007485644591678048, 'Genre_Country'),
 (0.006134410701285329, 'Genre_R&B;'),
 (0.00555867024024763, 'Genre_Latin'),
 (0.004126847694400286, 'Genre_Electronic'),
 (0.0036463175231112614, 'Genre_Religious'),
 (0.00202684674432187, 'Genre_Jazz'),
 (0.0015851139643564256, 'Genre_Reggae'),
 (0.001246243117396674, 'Genre_Vocal'),
 (0.001234156545106984, 'Genre_Stage & Screen'),
 (0.0008349050949068426, 'Genre_International'),
 (0.0007281098168644057, 'Genre_Blues'),
 (0.0007093155264729692, 'Genre_Folk'),
 (0.0003852323663834395, 'Genre_New Age'),
 (0.00030479497355150476, 'Ge

# Boosting

In [127]:
# Define the features set.
X = genre_binary_encoded.copy()
X = X.drop(["is_popular"], axis=1)
X.head()

danceability  energy  valence    tempo  loudness  acousticness  \
0         0.600   0.365    0.131  130.046   -13.083        0.0672   
1         0.670   0.531    0.336  139.385    -8.267        0.0156   
2         0.775   0.641    0.305  119.974    -6.718        0.0327   
3         0.775   0.641    0.305  119.974    -6.718        0.0327   
4         0.773   0.639    0.310  119.970    -6.738        0.0333   

   instrumentalness  liveness  speechiness  duration_ms  ...  \
0             0.585    0.0921       0.0498      437.200  ...   
1             0.345    0.3060       0.0377      431.293  ...   
2             0.000    0.1800       0.0380      243.013  ...   
3             0.000    0.1800       0.0380      243.013  ...   
4             0.000    0.1660       0.0380      243.240  ...   

   Genre_International  Genre_Jazz  Genre_Latin  Genre_New Age  \
0                    0           0            0              0   
1                    0           0            0              0   
2                    0           0            0              0   
3                    0           0            0              0   
4                    0           0            0              0   

   Genre_Pop/Rock  Genre_R&B;  Genre_Reggae  Genre_Religious  \
0               0           0             0                0   
1               0           0             0                0   
2               0           1             0                0   
3               0           1             0                0   
4               0           1             0                0   

   Genre_Stage & Screen  Genre_Vocal  
0                     0            0  
1                     0            0  
2                     0            0  
3                     0            0  
4                     0            0  

[5 rows x 29 columns]

In [128]:
y = genre_binary_encoded["is_popular"].ravel()
y[:5]

array([1, 1, 1, 1, 0], dtype=int64)

In [129]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1)

In [130]:
scaler = StandardScaler()
X_scaler = scaler.fit(X_train)
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [131]:
from sklearn.ensemble import GradientBoostingClassifier

# Create a classifier object
learning_rates = [0.05, 0.1, 0.25, 0.5, 0.75, 1]
for learning_rate in learning_rates:
    classifier = GradientBoostingClassifier(n_estimators=20,
                                            learning_rate=learning_rate,
                                            max_features=5,
                                            max_depth=3,
                                            random_state=0)

    # Fit the model
    classifier.fit(X_train_scaled, y_train)
    print("Learning rate: ", learning_rate)

    # Score the model
    print("Accuracy score (training): {0:.3f}".format(
        classifier.score(
            X_train_scaled,
            y_train)))
    print("Accuracy score (validation): {0:.3f}".format(
        classifier.score(
            X_test_scaled,
            y_test)))
    print()

Learning rate:  0.05
Accuracy score (training): 0.648
Accuracy score (validation): 0.639

Learning rate:  0.1
Accuracy score (training): 0.651
Accuracy score (validation): 0.639

Learning rate:  0.25
Accuracy score (training): 0.666
Accuracy score (validation): 0.647

Learning rate:  0.5
Accuracy score (training): 0.676
Accuracy score (validation): 0.650

Learning rate:  0.75
Accuracy score (training): 0.681
Accuracy score (validation): 0.649

Learning rate:  1
Accuracy score (training): 0.679
Accuracy score (validation): 0.648



In [132]:
boost_classifier = GradientBoostingClassifier(n_estimators=20,
   learning_rate=0.75, max_features=5, max_depth=3, random_state=0)

boost_classifier.fit(X_train_scaled, y_train)
boost_predictions = boost_classifier.predict(X_test_scaled)

In [133]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
boost_acc_score = accuracy_score(y_test, boost_predictions)
print(f"Accuracy Score : {boost_acc_score}")

Accuracy Score : 0.6494399685596385


In [134]:
boost_cm = confusion_matrix(y_test, boost_predictions)
boost_cm_df = pd.DataFrame(
   boost_cm, index=["Actual 0", "Actual 1"],
   columns=["Predicted 0", "Predicted 1"]
)
display(boost_cm_df)

Predicted 0  Predicted 1
Actual 0          341         1496
Actual 1          288         2964

In [135]:
print("Classification Report")
print(classification_report(y_test, boost_predictions))

Classification Report
              precision    recall  f1-score   support

           0       0.54      0.19      0.28      1837
           1       0.66      0.91      0.77      3252

    accuracy                           0.65      5089
   macro avg       0.60      0.55      0.52      5089
weighted avg       0.62      0.65      0.59      5089



In [136]:
model_performance_accuracy = pd.DataFrame({'Model': ['Logistic Regression', 
                                                      'RandomForest Classifier', 
                                                      'SVM',
                                                      'DecisionTree Classifier',
                                                      'Gradient Boost'],
                                            'Accuracy': [LR_accuracy,
                                                         rf_acc_score,
                                                         svm_accuracy,
                                                         dt_acc_score,
                                                         boost_acc_score]})

In [137]:
model_performance_accuracy.sort_values("Accuracy", ascending=False)

Model  Accuracy
1  RandomForest Classifier  0.660248
4           Gradient Boost  0.649440
2                      SVM  0.645706
0      Logistic Regression  0.640794
3  DecisionTree Classifier  0.598546